### ISSUE TITLE
Android Basics: Forage app

### ISSUE THREAD

**Issue by dogaegeozden** [google-developer-training/android-basics-kotlin-forage-app#18]
Initial build is failing and it's recommending to upgrade the gradle wrapper.

**Comment by dogaegeozden** [comment]
The starter code is not building and running

**Comment by zhvk** [comment]
You can apply the changes in the open pull request made by user secondsun: https://github.com/google-developer-training/android-basics-kotlin-forage-app/pull/3

I can confirm that these changes fix the build issues and now the starter code works.
