### ISSUE TITLE
Android Basics: Forage app----------YOU GUYS HAVE A INCOMPLETE IMPORT----URGENT!!!

### ISSUE THREAD

**Issue by jh115424** [google-developer-training/android-basics-kotlin-forage-app#5]
Can you please complete this import?    I can't do it, it is something YOU have too do.    I CANNOT run it until you fix.

It just says import R

Then re-upload a FINISHED starter code on the website.             Screenshot below
<img width="1440" alt="Screen Shot 2022-05-18 at 7 04 51 AM" src="https://user-images.githubusercontent.com/91148652/169034946-116b9162-ef6c-40b7-977d-92fa918928a3.png">

thanks!

**Comment by Gui88** [comment]
To import R you need to do it like this: 

`import [your app package name].R`

edit: looking at your screenshot, it looks like you have the [inventory app](https://github.com/google-developer-training/android-basics-kotlin-inventory-app) opened and not the forage app.

**Comment by jh115424** [comment]
The thing is, I did this project in the past and had no issues with the starter code.

I don't know why it magically changed.

Can you please tell me what it is?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jh115424** [comment]
Can you please get that addressed.


It also did it on a NEW project the developer team did.

The Sports app.

That has the same problem!    I can't run these projects until YOUR GUYS fix it on your end and upload a new starter code!

This is making me mad that 2 starter codes have an incomplete import.   And it won't let me fix on my end.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by kfrye** [comment]
Try running "invalidate caches" (from the File menu) and then rebuild your project. Android Studio is sometimes buggy and loses references.

**Comment by jh115424** [comment]
ok, thx.  I will try that.

Can you still forward that to the ones that made the starter codes in case?


Jennifer Hodge

Internet Sales

414-586-5425

Russ Darrow Honda


[cid:46ad999a-a28b-4fd5-8584-572f3dc6e06c]<https://your.tradeinvalet.com/tdhe0j>

________________________________

**Comment by jh115424** [comment]
That did not work.   That is something THEY need to fix on their end!

Please tell the developer team!

It is the Inventory app and the Doggler app.

The file is under the "build" section and will not let me change it!


Jennifer Hodge

Internet Sales

414-586-5425

Russ Darrow Honda


[cid:c5a01202-1d80-43d8-a955-ed8bf52654da]<https://your.tradeinvalet.com/tdhe0j>

________________________________

**Comment by kfrye** [comment]
I don't work for Google, but I know the developers are not going to be able to fix a file that is corrupted on your computer. If invalidate cache didn't work, copy any code you want to keep, delete the project, re-download the original starter code, and start again. The files in the "build" section are generated by Android Studio from the source code. The fact that it worked for you previously means that some file was corrupted at some point to cause the error. 

I had a project where the test code that wouldn't recognize any IDs that I had added to the project, although it recognized the old IDs, and the new IDs were accessible by the main part of the source code. Drove me crazy until I reset the cache and it magically fixed the problem. Android Studio is buggy.

Hope this helps. Good luck!

**Comment by jh115424** [comment]
oh, I thought you did.  sorry.

But yeah it wont let me.  I tried and when I run it, it gives the error message in Log cat and the R shows back up like I never did anything to fix it.


Jennifer Hodge

Internet Sales

414-586-5425

Russ Darrow Honda


[cid:f7791dfe-fbfe-44d2-a9b4-312ae19e1784]<https://your.tradeinvalet.com/tdhe0j>

________________________________

**Comment by jh115424** [comment]
I'll keep trying, otherwise I just can't run it.  I can put the codes in and do it for learning purposes.(its one of those projects where they do not walk you through it)


Jennifer Hodge

Internet Sales

414-586-5425

Russ Darrow Honda


[cid:ddbf0295-b01a-47d2-b006-503e5b12cd0d]<https://your.tradeinvalet.com/tdhe0j>

________________________________

**Comment by jh115424** [comment]
Ok, I tried doing it, ran it and it deleted itself and is back to R.

It should save.     Can you please look into this?


It was no problems with this as everything  was there when I did the project last year.


Thanks

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by kemicky** [comment]
#To Clear the errors.. you need to follow:
-  Tutor's instructions, it is like a puzzle requires thinking
-  Fill in the todo lines 
-  use the Inventory App codes as example but changing the name to the hint given by the tutor
#See attached:
![Screenshot 2022-11-21 at 10 40 52](https://user-images.githubusercontent.com/57273086/203004592-3618a88e-06b6-4bf2-a87e-b91e54493af7.png)
